exports.listAllRolePermission = [
    {
        id: 1,
        label: 'List and Detail',
        name: 'List',
        modules: 'core_bank_list core_bank_detail',
        menu: 'Bank',
    },
    {
        id: 2,
        label: 'Add',
        name: 'Add',
        modules: 'core_bank_new',
        menu: 'Bank',
    },
    {
        id: 3,
        label: 'Edit',
        name: 'Edit',
        modules: 'core_bank_patch',
        menu: 'Bank',
    },
    {
        id: 4,
        label: 'Approval',
        name: 'Approval',
        modules: 'core_bank_approval',
        menu: 'Bank',
    },
    {
        id: 5,
        label: 'List and Detail',
        name: 'List',
        modules: 'core_borrower_get_all core_borrower_get_details',
        menu: 'Nasabah',
    },
    {
        id: 6,
        label: 'Add',
        name: 'Add',
        modules: 'core_borrower_new',
        menu: 'Nasabah',
    },
    {
        id: 7,
        label: 'Edit',
        name: 'Edit',
        modules: 'core_borrower_patch',
        menu: 'Nasabah',
    },
    {
        id: 8,
        label: 'Approval',
        name: 'Approval',
        modules: 'core_borrower_approval',
        menu: 'Nasabah',
    },
    {
        id: 9,
        label: 'List and Detail',
        name: 'List',
        modules: 'core_loan_get_all core_loan_get_details',
        menu: 'Pinjaman',
    },
    {
        id: 10,
        label: 'Add',
        name: 'Add',
        modules: 'core_loan_new',
        menu: 'Pinjaman',
    },
    {
        id: 11,
        label: 'Edit',
        name: 'Edit',
        modules: 'core_loan_patch',
        menu: 'Pinjaman',
    },
    {
        id: 12,
        label: 'Approval',
        name: 'Approval',
        modules: 'core_loan_approval',
        menu: 'Pinjaman',
    },
    {
        id: 13,
        label: 'List and Detail',
        name: 'List',
        modules: 'core_service_list core_service_detail',
        menu: 'Layanan',
    },
    {
        id: 14,
        label: 'Add',
        name: 'Add',
        modules: 'core_service_new',
        menu: 'Layanan',
    },
    {
        id: 15,
        label: 'Edit',
        name: 'Edit',
        modules: 'core_service_patch',
        menu: 'Layanan',
    },
    {
        id: 16,
        label: 'Approval',
        name: 'Approval',
        modules: 'core_service_approval',
        menu: 'Layanan',
    },
    {
        id: 17,
        label: 'List and Detail',
        name: 'List',
        modules: 'core_product_list core_product_detail',
        menu: 'Produk',
    },
    {
        id: 18,
        label: 'Add',
        name: 'Add',
        modules: 'core_product_new',
        menu: 'Produk',
    },
    {
        id: 19,
        label: 'Edit',
        name: 'Edit',
        modules: 'core_product_patch',
        menu: 'Produk',
    },
    {
        id: 20,
        label: 'Approval',
        name: 'Approval',
        modules: 'core_product_approval',
        menu: 'Produk',
    },
    {
        id: 21,
        label: 'List and Detail',
        name: 'List',    
        modules: 'core_bank_type_list core_bank_type_detail',
        menu: 'Tipe Bank',
    },
    {
        id: 22,
        label: 'Add',
        name: 'Add',
        modules: 'core_bank_type_new',
        menu: 'Tipe Bank',
    },
    {
        id: 23,
        label: 'Edit',
        name: 'Edit',
        modules: 'core_bank_type_patch',
        menu: 'Tipe Bank',
    },
    {
        id: 24,
        label: 'Approval',
        name: 'Approval',
        modules: 'core_bank_type_approval',
        menu: 'Tipe Bank',
    },
    {
        id: 25,
        label: 'List and Detail',
        name: 'List',
        modules: 'core_loan_purpose_list core_loan_purpose_detail',
        menu: 'Tujuan',
    },
    {
        id: 26,
        label: 'Add',
        name: 'Add',
        modules: 'core_loan_purpose_new',
        menu: 'Tujuan',
    },
    {
        id: 27,
        label: 'Edit',
        name: 'Edit',
        modules: 'core_loan_purpose_patch',
        menu: 'Tujuan',
    },
    {
        id: 28,
        label: 'Approval',
        name: 'Approval',
        modules: 'core_loan_purpose_approval',
        menu: 'Tujuan',
    },
    {
        id: 29,
        label: 'List and Detail',
        name: 'List',
        modules: 'core_role_list core_role_details',
        menu: 'Role',
    },
    {
        id: 30,
        label: 'Add',
        name: 'Add',
        modules: 'core_role_new',
        menu: 'Role',
    },
    {
        id: 31,
        label: 'Edit',
        name: 'Edit',
        modules: 'core_role_patch',
        menu: 'Role',
    },
    {
        id: 32,
        label: 'Approval',
        name: 'Approval',
        modules: 'core_role_approval',
        menu: 'Role',
    },
    {
        id: 33,
        label: 'List and Detail',
        name: 'List',
        modules: 'core_permission_list core_permission_detail',
        menu: 'Role Permission',
    },
    {
        id: 34,
        label: 'Add',
        name: 'Add',
        modules: 'core_permission_new',
        menu: 'Role Permission',
    },
    {
        id: 35,
        label: 'Edit',
        name: 'Edit',
        modules: 'core_permission_patch',
        menu: 'Role Permission',
    },
    {
        id: 36,
        label: 'Approval',
        name: 'Approval',
        modules: 'core_permission_approval',
        menu: 'Role Permission',
    },
    {
        id: 37,
        label: 'List and Detail',
        name: 'List',
        modules: 'core_user_list core_user_details',
        menu: 'Akun',
    },
    {
        id: 38,
        label: 'Add',
        name: 'Add',
        modules: 'core_user_new',
        menu: 'Akun',
    },
    {
        id: 39,
        label: 'Edit',
        name: 'Edit',
        modules: 'core_user_patch',
        menu: 'Akun',
    },
    {
        id: 40,
        label: 'Approval',
        name: 'Approval',
        modules: 'core_user_approval',
        menu: 'Akun',
    },
    {
        id: 41,
        label: 'List and Detail',
        name: 'List',
        modules: 'convenience_fee_report',
        menu: 'Report',
    },
    {
        id: 42,
        label: 'Add',
        name: 'Add',
        modules: 'convenience_fee_report_new',
        menu: 'Report',
    },
    {
        id: 43,
        label: 'Edit',
        name: 'Edit',
        modules: 'convenience_fee_report_patch',
        menu: 'Report',
    },
    {
        id: 44,
        label: 'Approval',
        name: 'Approval',
        modules: 'convenience_fee_report_approval',
        menu: 'Report',
    },
  ]